
package com.themangoproject.ui;

import javax.swing.ComboBoxModel;

/**
 * AddSubtractInnerPanel is a panel that is used to gather information using
 * two combo boxes and a textfield.
 * 
 * @author  Kyle Ronning
 * @version 12-14-2008
 */
public class AddSubtractInnerPanel extends javax.swing.JPanel {

    /** 
     * Creates a new AddSubtractInnerPanel.
     * 
     * @param cbm1 ComboBoxModel for the left ComboBox
     * @param cbm2 ComboBoxModel for the right ComboBox
     */
    public AddSubtractInnerPanel(ComboBoxModel cbm1, ComboBoxModel cbm2) {
        initComponents();
        this.jComboBox1.setModel(cbm1);
        this.jComboBox2.setModel(cbm2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(442, 35));

        jComboBox1.setMaximumRowCount(5);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/themangoproject/ui/images/add.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/themangoproject/ui/images/minus.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox1, jComboBox2, jTextField1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox1, jComboBox2, jTextField1});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton3});

    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Add Button
    // Adds a panel like itself to the parent JPanel
    ((AddSubtractPanel)
            (this.getParent().getParent().getParent().getParent())).addAddSubPanel();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // Subtract Button
    // Removes this panel from the parent JPanel.
    ((AddSubtractPanel)
            (this.getParent().getParent().getParent().getParent())).removeAddSubPanel(this);
}//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
   
    /**
     * Disable the minus button in this panel.
     */
    public void disableMinusButton() {
        this.jButton3.setEnabled(false);
    }
    
    /**
     * Enable the minus button in this panel.
     */
    public void enableMinusButton() {
        this.jButton3.setEnabled(true);
    }
    
    /**
     * Gets the left combo box.
     * 
     * @return The left combo box.
     */
    public Object getLeftComboObject() {
        return this.jComboBox1;
    }
    
    /**
     * Gets the right combo box.
     * 
     * @return The right combo box.
     */
    public Object getRightComboObject() {
        return this.jComboBox2;
    }
    
    /**
     * Gets the text in the text field.
     * 
     * @return The text in the text field.
     */
    public String getTextFieldText() {
        return this.jTextField1.getText();
    }
    
    /**
     * Set the first ComboBox editable.
     * 
     * @param edit Sets the first ComboBox editable if true.
     */
    public void setComboBox1Editable(boolean edit) {
        this.jComboBox1.setEditable(edit);
    }
    
    /**
     * Set the second ComboBox editable.
     * 
     * @param edit Sets the second ComboBox editable if true.
     */
    public void setComboBox2Editable(boolean edit) {
        this.jComboBox2.setEditable(edit);
    }
    
    /**
     * Selects the given item in the left combo box from a given string.
     * 
     * @param name The name of the item.
     */
    public void setSelectedLeftComboBox(String name) {
        this.jComboBox1.setSelectedItem(name);
    }
    
    /**
     * Selects the given item in the right combo box from a given string.
     * 
     * @param name The name of the item.
     */
    public void setSelectedRightComboBox(String name) {
        this.jComboBox2.setSelectedItem(name);
    }
    
    /**
     * Sets the text of the text field.
     * 
     * @param text The text to set in the text field.
     */
    public void setTextFieldText(String text) {
        this.jTextField1.setText(text);
    }
}
