/*
 * AddSubstractDaddyPanel.java
 *
 * Created on November 20, 2008, 9:20 PM
 */

package com.themangoproject.ui;

import java.util.ArrayList;

/**
 *
 * @author  kronning
 */
public class AddSubstractPanel extends javax.swing.JPanel {

    /** Creates new form AddSubstractDaddyPanel */
    public AddSubstractPanel() {
        initComponents();
        //this.orderTracker.add(this.addSubtractDropDownPanel1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSubtractDropDownPanel1 = new com.themangoproject.ui.AddSubtractInnerPanel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 1));

        this.addSubtractDropDownPanel1.disableMinusButton();
        add(addSubtractDropDownPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.themangoproject.ui.AddSubtractInnerPanel addSubtractDropDownPanel1;
    // End of variables declaration//GEN-END:variables
    
    //private ArrayList<AddSubtractDropDownPanel> orderTracker = new ArrayList<AddSubtractDropDownPanel>();
    
    public void addAddSubPanel() {
        this.add(new AddSubtractInnerPanel());
        if (this.getComponentCount() == 2)
            ((AddSubtractInnerPanel)this.getComponent(0)).enableMinusButton();
        else if (this.getComponentCount() == 10) {
            for (int i = 0; i < 10; i++) {
                // disable all + buttons
                ((AddSubtractInnerPanel)
                        this.getComponent(i)).disablePlusButton();
            }
        } 
//System.out.println(this.getComponentCount());        
        this.validate();
        this.repaint();
        }
    
    public void removeAddSubPanel(AddSubtractInnerPanel a) {
        this.remove(a);
        if (this.getComponentCount() == 9) {
            for (int i = 0; i < 9; i++) {
                // disable all + buttons
                ((AddSubtractInnerPanel)
                        this.getComponent(i)).enablePlusButton();
            }            
        }
        else if (this.getComponentCount() == 1) {
            // Disable the one - button
            ((AddSubtractInnerPanel)
                    this.getComponent(0)).disableMinusButton();        
        }
//System.out.println(this.getComponentCount());        
        this.validate();
        this.repaint();
    }
    
      
}
