/*
 * AddSubstractDaddyPanel.java
 *
 * Created on November 20, 2008, 9:20 PM
 */

package com.themangoproject.ui;

import javax.swing.Box;

/**
 * AddSubstractPanel is a panel to collect AddSubtractInnerPanels.
 * 
 * @author  Kyle Ronning
 * @version 1.0
 */
public class AddSubstractPanel extends javax.swing.JPanel {

    /** Creates new form AddSubstractDaddyPanel */
    public AddSubstractPanel() {
        initComponents();
        // Add a glue component to take up extra space so the panels that
        // are added aren't stretched.
        this.jPanel1.add(Box.createVerticalGlue(), 1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        addSubtractInnerPanel1 = new com.themangoproject.ui.AddSubtractInnerPanel();

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        // Disable the minus button
        this.addSubtractInnerPanel1.disableMinusButton();
        jPanel1.add(addSubtractInnerPanel1);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.themangoproject.ui.AddSubtractInnerPanel addSubtractInnerPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Adds an AddSubtractInnerPanel to this panel.
     */
    public void addAddSubPanel() {
        this.jPanel1.add(new AddSubtractInnerPanel(), 
                this.jPanel1.getComponentCount() - 1);
        if (this.jPanel1.getComponentCount() == 3)
            ((AddSubtractInnerPanel)this.jPanel1.getComponent(0)).enableMinusButton();
        //else if (this.getComponentCount() == 10) {
        //    for (int i = 0; i < 10; i++) {
                // disable all + buttons
        //        ((AddSubtractInnerPanel)
        //                this.getComponent(i)).disablePlusButton();
        //    }
        //}        
        this.jPanel1.revalidate();
        this.jPanel1.repaint();
    }
    
    /**
     * Removes an AddSubtractInnerPanel from this panel.
     * @param a The AddSubtractInnerPanel to remove from this panel.
     */
    public void removeAddSubPanel(AddSubtractInnerPanel a) {
        this.jPanel1.remove(a);
        //if (this.getComponentCount() == 9) {
        //    for (int i = 0; i < 9; i++) {
                // disable all + buttons
        //        ((AddSubtractInnerPanel)
        //                this.getComponent(i)).enablePlusButton();
        //    }            
        //}
        if (this.jPanel1.getComponentCount() == 2) {
            // Disable the one - button
            ((AddSubtractInnerPanel)
                    this.jPanel1.getComponent(0)).disableMinusButton();        
        }        
        this.jPanel1.revalidate();
        this.jPanel1.repaint();
    }
         
}
