package com.themangoproject.ui;

import com.themangoproject.webservice.AmazonMovieTitleQuery.AmazonMovieTitleResult;
import java.util.ArrayList;
import javax.swing.SwingWorker;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author  Paul Osborne
 */
public class AmazonQueryFrame extends javax.swing.JDialog {

    /** Generated serial UID */
	private static final long serialVersionUID = 4084685608291384549L;
	
	private SwingWorker<String, Object> amazonQueryWorker;
    private ArrayList<ChangeListener> asinChangeListeners;
	
	/** Creates new form AmazonQueryFrame */
    public AmazonQueryFrame(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        asinChangeListeners = new ArrayList<ChangeListener>();
        amazonQueryWorker = new SwingWorker<String, Object>() {
			@Override
			protected String doInBackground() throws Exception {
				queryButton.setText("Working...");
				queryButton.setEnabled(false);
				AmazonQueryResultsListModel model = (AmazonQueryResultsListModel) queryResultsList.getModel();
			    model.setQuery(titleQueryTextField.getText());
			    return "Done";
			}
			@Override
			protected void done() {
				queryButton.setText("Query");
				queryButton.setEnabled(true);
			}
        };
    }
    
    public void setSearchQuery(String titleQuery) {
        ((AmazonQueryResultsListModel)this.queryResultsList.getModel()).setQuery(titleQuery);
    }

    public void addASINChangeListener(ChangeListener cl) {
        this.asinChangeListeners.add(cl);
    }
    
    public void removeASINChangeListener(ChangeListener cl) {
        this.asinChangeListeners.remove(cl);
    }
    
    private void fireASINEvent(String asin) {
        for (ChangeListener cl : asinChangeListeners) {
            cl.stateChanged(new ChangeEvent(asin));
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titleQueryTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryResultsList = new javax.swing.JList();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        queryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Query Amazon");

        jLabel1.setText("Title:");

        titleQueryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleQueryTextFieldActionPerformed(evt);
            }
        });

        queryResultsList.setModel(new AmazonQueryResultsListModel());
        jScrollPane1.setViewportView(queryResultsList);

        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        queryButton.setText("Search");
        queryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleQueryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(queryButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acceptButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(queryButton)
                    .addComponent(titleQueryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void titleQueryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleQueryTextFieldActionPerformed

}//GEN-LAST:event_titleQueryTextFieldActionPerformed

private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
    int selIndex = queryResultsList.getSelectedIndex();
    AmazonQueryResultsListModel model = (AmazonQueryResultsListModel) queryResultsList.getModel();
    AmazonMovieTitleResult result = model.getAmazonQueryResult(selIndex);
    fireASINEvent(result.getASIN());
    this.dispose();
}//GEN-LAST:event_acceptButtonActionPerformed

private void queryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryButtonActionPerformed
    amazonQueryWorker.execute();
}//GEN-LAST:event_queryButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AmazonQueryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton queryButton;
    private javax.swing.JList queryResultsList;
    private javax.swing.JTextField titleQueryTextField;
    // End of variables declaration//GEN-END:variables

}
