package com.themangoproject.ui;

import com.themangoproject.ui.model.MangoTableModelIF;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * ItemInfoPanel is a panel that displays an image associated with the
 * selected movie in the table.
 * 
 * @author Kyle Ronning, Zach Varberg, Paul Osborne
 * @version 1.0
 */
public class ItemInfoPanel extends javax.swing.JPanel implements
        ListSelectionListener {

    /** Creates new form ItemInfoPanel */
    public ItemInfoPanel() {
        initComponents();
        // Set default image
        this.setThumbnailImage(null);
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coverArtLabel = new javax.swing.JLabel();

        coverArtLabel
                .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coverArtLabel.setAlignmentX(0.5F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(coverArtLabel,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 196,
                        Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(coverArtLabel,
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 173,
                        Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coverArtLabel;

    // End of variables declaration//GEN-END:variables

    /**
     * Set the image in the panel to correspond to the image for the
     * selected movie in the table.
     */
    public void setThumbnailImage(Image image) {
        if (image != null) {
            this.coverArtLabel.setIcon(new ImageIcon(image));
        } else {
            Image im = new ImageIcon(
                    getClass()
                            .getResource(
                                    "/com/themangoproject/ui/images/defaultMangoLogo.jpg"))
                    .getImage();
            this.coverArtLabel
                    .setIcon(new ImageIcon(im.getScaledInstance(160,
                            160, Image.SCALE_DEFAULT)));
        }
    }

    /**
     * List selection listener for movie selections.
     * 
     * @param lse
     *            The list selection event.
     */
    public void valueChanged(ListSelectionEvent lse) {
        try {
            JTable table = UIController.getInstance().getViewTable();
            int viewRow = table.getSelectedRow();
            if (viewRow < 0) {
                return;
            }
            int modelRow = table.getRowSorter()
                    .convertRowIndexToModel(viewRow);
            MangoTableModelIF tm = (MangoTableModelIF) table
                    .getModel();
            Image i = tm.getImageForRow(modelRow);
            setThumbnailImage(i);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
