package com.themangoproject.ui;

import javax.swing.JTree;

/**
 * The NavigatorPanel is the tree on the left to view your movie
 * collection.
 * 
 * @author Paul Osborne
 */
public class NavigatorPanel extends javax.swing.JPanel {

    /** Creates new form NavigatorPanel */
    public NavigatorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        navigatorTree = new com.themangoproject.ui.NavigatorJTree();

        jScrollPane1.setViewportView(navigatorTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 199,
                        Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 414,
                        Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.themangoproject.ui.NavigatorJTree navigatorTree;

    // End of variables declaration//GEN-END:variables

    /**
     * Gets the navigator tree.
     * 
     * @return the navigator tree.
     */
    public JTree getNavigatorTree() {
        return this.navigatorTree;
    }

}
